# Generated by Django 4.0.5 on 2022-06-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_register',
            name='tphone',
            field=models.BigIntegerField(),
        ),
    ]
