# Generated by Django 4.0.5 on 2022-06-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainerapp', '0002_alter_trainer_register_tphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_register',
            name='temail',
            field=models.CharField(max_length=50),
        ),
    ]
