# Generated by Django 4.0.5 on 2022-06-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainerapp', '0003_alter_trainer_register_temail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_assign',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
